//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tell us more about your organization.
        /// </summary>
        internal static string AboutTheAccount {
            get {
                return ResourceManager.GetString("AboutTheAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Organization Category.
        /// </summary>
        internal static string AccountCategory {
            get {
                return ResourceManager.GetString("AccountCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Organization Category (Other).
        /// </summary>
        internal static string AccountCategoryOthers {
            get {
                return ResourceManager.GetString("AccountCategoryOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Organization Name.
        /// </summary>
        internal static string AccountName {
            get {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Organization Phone Number.
        /// </summary>
        internal static string AccountPhone {
            get {
                return ResourceManager.GetString("AccountPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Any additional information we should know?.
        /// </summary>
        internal static string AdditionalInformationEvent {
            get {
                return ResourceManager.GetString("AdditionalInformationEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close.
        /// </summary>
        internal static string btnClose {
            get {
                return ResourceManager.GetString("btnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Go to top.
        /// </summary>
        internal static string BtnGoTo {
            get {
                return ResourceManager.GetString("BtnGoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Submit.
        /// </summary>
        internal static string BtnRegister {
            get {
                return ResourceManager.GetString("BtnRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email Address.
        /// </summary>
        internal static string ContactEmail {
            get {
                return ResourceManager.GetString("ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm email address.
        /// </summary>
        internal static string ContactEmailConfirm {
            get {
                return ResourceManager.GetString("ContactEmailConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First Name.
        /// </summary>
        internal static string ContactFirstName {
            get {
                return ResourceManager.GetString("ContactFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Best way to Contact you.
        /// </summary>
        internal static string ContactForm {
            get {
                return ResourceManager.GetString("ContactForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last Name.
        /// </summary>
        internal static string ContactLastName {
            get {
                return ResourceManager.GetString("ContactLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone Number.
        /// </summary>
        internal static string ContactPhone {
            get {
                return ResourceManager.GetString("ContactPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Will the event take place at Raising Cane&apos;s or at another address?.
        /// </summary>
        internal static string EventAddress {
            get {
                return ResourceManager.GetString("EventAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a City.
        /// </summary>
        internal static string EventCity {
            get {
                return ResourceManager.GetString("EventCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Country.
        /// </summary>
        internal static string EventCountry {
            get {
                return ResourceManager.GetString("EventCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Event Date.
        /// </summary>
        internal static string EventDate {
            get {
                return ResourceManager.GetString("EventDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Event Name.
        /// </summary>
        internal static string EventDescription {
            get {
                return ResourceManager.GetString("EventDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please inform if the event address will be based on the Restaurant address or if it will be another one.
        /// </summary>
        internal static string EventOtherAddress {
            get {
                return ResourceManager.GetString("EventOtherAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a State/Province (i.e. TX, OH,AZ).
        /// </summary>
        internal static string EventState {
            get {
                return ResourceManager.GetString("EventState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Address.
        /// </summary>
        internal static string EventStreet {
            get {
                return ResourceManager.GetString("EventStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Event Time.
        /// </summary>
        internal static string EventTime {
            get {
                return ResourceManager.GetString("EventTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ZIP/Postal code.
        /// </summary>
        internal static string EventZip {
            get {
                return ResourceManager.GetString("EventZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Where do you want to host the Event?.
        /// </summary>
        internal static string HostEvent {
            get {
                return ResourceManager.GetString("HostEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a How RC supported this event in the past?.
        /// </summary>
        internal static string HowSupportedEvent {
            get {
                return ResourceManager.GetString("HowSupportedEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you have any ideas on how you would like Raising Cane’s to help?.
        /// </summary>
        internal static string IdeasRCEvent {
            get {
                return ResourceManager.GetString("IdeasRCEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loading.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error has occurred while submitting this request. Please try again later or contact us &lt;a href=&quot;http://commentform.marketforce.com/commentform/raisingcanes.aspx&quot;&gt;here&lt;/a&gt;.
        /// </summary>
        internal static string MSGNOOK {
            get {
                return ResourceManager.GetString("MSGNOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You&apos;ll receive an e-mail acknowledging that we&apos;ve received your request shortly. Our standard turnaround time for requests is 3-6 weeks..
        /// </summary>
        internal static string MSGOK {
            get {
                return ResourceManager.GetString("MSGOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Saving data.
        /// </summary>
        internal static string MSGSavingData {
            get {
                return ResourceManager.GetString("MSGSavingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a How many people do you expect to attend or support your event?.
        /// </summary>
        internal static string PeopleEvent {
            get {
                return ResourceManager.GetString("PeopleEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Restaurant.
        /// </summary>
        internal static string PreferredRestaurant {
            get {
                return ResourceManager.GetString("PreferredRestaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a What is the purpose or goal of the event?.
        /// </summary>
        internal static string PurposeEvent {
            get {
                return ResourceManager.GetString("PurposeEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restaurant Location.
        /// </summary>
        internal static string Restaurant {
            get {
                return ResourceManager.GetString("Restaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search Radius.
        /// </summary>
        internal static string SearchRadius {
            get {
                return ResourceManager.GetString("SearchRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a State.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Street.
        /// </summary>
        internal static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has Raising Cane&apos;s supported this event in the past?.
        /// </summary>
        internal static string SupportedEvent {
            get {
                return ResourceManager.GetString("SupportedEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Complete the data (TBD Webpage layout).
        /// </summary>
        internal static string TitlePage {
            get {
                return ResourceManager.GetString("TitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Upload any additional information documents about your event here (Max file size limit 10 Mb).
        /// </summary>
        internal static string UploadAdditionalInfEvent {
            get {
                return ResourceManager.GetString("UploadAdditionalInfEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Raising Cane’s requires a W9 in order to provide funds from a Fundraiser or for a sponsorship. If you have your W-9 available, please upload here.
        /// </summary>
        internal static string UploadW9Event {
            get {
                return ResourceManager.GetString("UploadW9Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is there a specific Raising Cane’s Restaurant you typically work with? If no, your request will be routed to the Restaurant closest to your organization address..
        /// </summary>
        internal static string UsualRestaurant {
            get {
                return ResourceManager.GetString("UsualRestaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ZIP Code.
        /// </summary>
        internal static string Zip {
            get {
                return ResourceManager.GetString("Zip", resourceCulture);
            }
        }
    }
}
