//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell us more about your organization.
        /// </summary>
        internal static string AboutTheAccount {
            get {
                return ResourceManager.GetString("AboutTheAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Category.
        /// </summary>
        internal static string AccountCategory {
            get {
                return ResourceManager.GetString("AccountCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Category (Other).
        /// </summary>
        internal static string AccountCategoryOthers {
            get {
                return ResourceManager.GetString("AccountCategoryOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Name.
        /// </summary>
        internal static string AccountName {
            get {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Phone Number.
        /// </summary>
        internal static string AccountPhone {
            get {
                return ResourceManager.GetString("AccountPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any additional information we should know?.
        /// </summary>
        internal static string AdditionalInformationEvent {
            get {
                return ResourceManager.GetString("AdditionalInformationEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string btnClose {
            get {
                return ResourceManager.GetString("btnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to top.
        /// </summary>
        internal static string BtnGoTo {
            get {
                return ResourceManager.GetString("BtnGoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string BtnRegister {
            get {
                return ResourceManager.GetString("BtnRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string ContactEmail {
            get {
                return ResourceManager.GetString("ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm email address.
        /// </summary>
        internal static string ContactEmailConfirm {
            get {
                return ResourceManager.GetString("ContactEmailConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string ContactFirstName {
            get {
                return ResourceManager.GetString("ContactFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best way to Contact you.
        /// </summary>
        internal static string ContactForm {
            get {
                return ResourceManager.GetString("ContactForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string ContactLastName {
            get {
                return ResourceManager.GetString("ContactLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string ContactPhone {
            get {
                return ResourceManager.GetString("ContactPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will the event take place at Raising Cane&apos;s or at another address?.
        /// </summary>
        internal static string EventAddress {
            get {
                return ResourceManager.GetString("EventAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string EventCity {
            get {
                return ResourceManager.GetString("EventCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string EventCountry {
            get {
                return ResourceManager.GetString("EventCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Date.
        /// </summary>
        internal static string EventDate {
            get {
                return ResourceManager.GetString("EventDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Name.
        /// </summary>
        internal static string EventDescription {
            get {
                return ResourceManager.GetString("EventDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please inform if the event address will be based on the Restaurant address or if it will be another one.
        /// </summary>
        internal static string EventOtherAddress {
            get {
                return ResourceManager.GetString("EventOtherAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State/Province (i.e. TX, OH,AZ).
        /// </summary>
        internal static string EventState {
            get {
                return ResourceManager.GetString("EventState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string EventStreet {
            get {
                return ResourceManager.GetString("EventStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Time.
        /// </summary>
        internal static string EventTime {
            get {
                return ResourceManager.GetString("EventTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP/Postal code.
        /// </summary>
        internal static string EventZip {
            get {
                return ResourceManager.GetString("EventZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where do you want to host the Event?.
        /// </summary>
        internal static string HostEvent {
            get {
                return ResourceManager.GetString("HostEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How RC supported this event in the past?.
        /// </summary>
        internal static string HowSupportedEvent {
            get {
                return ResourceManager.GetString("HowSupportedEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have any ideas on how you would like Raising Cane’s to help?.
        /// </summary>
        internal static string IdeasRCEvent {
            get {
                return ResourceManager.GetString("IdeasRCEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while submitting this request. Please try again later or contact us &lt;a href=&quot;http://commentform.marketforce.com/commentform/raisingcanes.aspx&quot;&gt;here&lt;/a&gt;.
        /// </summary>
        internal static string MSGNOOK {
            get {
                return ResourceManager.GetString("MSGNOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ll receive an e-mail acknowledging that we&apos;ve received your request shortly. Our standard turnaround time for requests is 3-6 weeks..
        /// </summary>
        internal static string MSGOK {
            get {
                return ResourceManager.GetString("MSGOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving data.
        /// </summary>
        internal static string MSGSavingData {
            get {
                return ResourceManager.GetString("MSGSavingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many people do you expect to attend or support your event?.
        /// </summary>
        internal static string PeopleEvent {
            get {
                return ResourceManager.GetString("PeopleEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Restaurant.
        /// </summary>
        internal static string PreferredRestaurant {
            get {
                return ResourceManager.GetString("PreferredRestaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the purpose or goal of the event?.
        /// </summary>
        internal static string PurposeEvent {
            get {
                return ResourceManager.GetString("PurposeEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant Location.
        /// </summary>
        internal static string Restaurant {
            get {
                return ResourceManager.GetString("Restaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        internal static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Raising Cane&apos;s supported this event in the past?.
        /// </summary>
        internal static string SupportedEvent {
            get {
                return ResourceManager.GetString("SupportedEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete the data (TBD Webpage layout).
        /// </summary>
        internal static string TitlePage {
            get {
                return ResourceManager.GetString("TitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload any additional information documents about your event here (Max file size limit 10 Mb).
        /// </summary>
        internal static string UploadAdditionalInfEvent {
            get {
                return ResourceManager.GetString("UploadAdditionalInfEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raising Cane’s requires a W9 in order to provide funds from a Fundraiser or for a sponsorship. If you have your W-9 available, please upload here.
        /// </summary>
        internal static string UploadW9Event {
            get {
                return ResourceManager.GetString("UploadW9Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is there a specific Raising Cane’s Restaurant you typically work with? If no, your request will be routed to the Restaurant closest to your organization address..
        /// </summary>
        internal static string UsualRestaurant {
            get {
                return ResourceManager.GetString("UsualRestaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP Code.
        /// </summary>
        internal static string Zip {
            get {
                return ResourceManager.GetString("Zip", resourceCulture);
            }
        }
    }
}
